# Copy these contents into the root directory of your Github project in a file
# named .travis.yml

# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.
language: c

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

matrix:
  include:
  - env: BUILD=stack ARGS="--resolver lts-6"
    compiler: ": #stack ghc 7.10.3"
    addons: {apt: {packages: [libgmp,libgmp-dev]}}
  - env: BUILD=stack ARGS="--resolver lts-7"
    compiler: ": #stack ghc 8.0.1"
    addons: {apt: {packages: [libgmp,libgmp-dev]}}
  - env: BUILD=stack ARGS="--resolver nightly"
    compiler: ": #stack nightly"
    addons: {apt: {packages: [libgmp,libgmp-dev]}}
  allow_failures:
  - env: BUILD=stack ARGS="--resolver nightly"

before_install:
# Using compiler above sets CC to an invalid value, so unset it
- unset CC

# Download and unpack the stack executable
- export PATH=$HOME/.local/bin:$PATH
- mkdir -p ~/.local/bin
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
- stack --no-terminal --install-ghc $ARGS test --haddock --no-haddock-deps
