# Copy these contents into the root directory of your Github project in a file
# named .travis.yml

# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

matrix:
  include:
  - env: BUILD=stack ARGS="--resolver lts-13"
    compiler: ": #stack ghc 8.6.4"
    addons: {apt: {packages: [libgmp-dev]}}
  - env: BUILD=stack ARGS="--resolver lts-14"
    compiler: ": #stack ghc 8.6.5"
    addons: {apt: {packages: [libgmp-dev]}}
  - env: BUILD=stack ARGS="--resolver nightly"
    compiler: ": #stack nightly"
    addons: {apt: {packages: [libgmp-dev]}}
  allow_failures:
  - env: BUILD=stack ARGS="--resolver nightly"

before_install:
# Using compiler above sets CC to an invalid value, so unset it
- unset CC

# Download and unpack the stack executable
- export PATH=$HOME/.local/bin:$PATH
- mkdir -p ~/.local/bin
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz 4 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack --no-terminal --install-ghc test --only-dependencies

script:
- stack --no-terminal $ARGS test --haddock --no-haddock-deps
